option(VEYRA_ENABLE_AJA "Native AJA KONA HDMI input via MIT NTV2 SDK" OFF)
set(VEYRA_AJA_SDK_ROOT "" CACHE PATH "External pinned AJA NTV2 SDK checkout")
if(VEYRA_ENABLE_AJA)
  if(NOT EXISTS "${VEYRA_AJA_SDK_ROOT}/CMakeLists.txt")
    message(FATAL_ERROR "VEYRA_ENABLE_AJA requires VEYRA_AJA_SDK_ROOT")
  endif()
  set(AJA_BUILD_APPS OFF CACHE BOOL "" FORCE)
  set(AJA_BUILD_DRIVER OFF CACHE BOOL "" FORCE)
  set(AJA_BUILD_QT_BASED OFF CACHE BOOL "" FORCE)
  set(AJA_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(AJA_BUILD_LIBS ON CACHE BOOL "" FORCE)
  set(AJA_BUILD_SHARED OFF CACHE BOOL "" FORCE)
  add_subdirectory("${VEYRA_AJA_SDK_ROOT}" "${CMAKE_BINARY_DIR}/aja-sdk" EXCLUDE_FROM_ALL)
  target_link_libraries(veyra_sources PRIVATE ajantv2)
  target_compile_definitions(veyra_sources PRIVATE VEYRA_ENABLE_AJA=1 MSWindows AJA_WINDOWS NTV2_USE_CPLUSPLUS11)
endif()

if(VEYRA_ENABLE_AJA)
  add_executable(veyra_aja_capture_tests tests/integration/AjaCaptureTests.cpp)
  target_compile_features(veyra_aja_capture_tests PRIVATE cxx_std_20)
  target_compile_options(veyra_aja_capture_tests PRIVATE /utf-8)
  target_link_libraries(veyra_aja_capture_tests PRIVATE veyra_sources)
endif()
